### ISSUE TITLE
prometheus metrics

### ISSUE THREAD

**Issue by appliedprivacy** [DNSCrypt/doh-server#63]
Hi Frank,

thanks for the great event yesterday!

We noticed https://github.com/DNSCrypt/encrypted-dns-server has prometheus metrics,
will there also be prometheus metrics in doh-server (especially for the ODoH part)? 

thanks!

btw: we are looking forward to the release of the ODoH relay code!

**Comment by jedisct1** [comment]
Hi!

And thanks for attending yesterday's event, and putting up with my complete inability to handle streaming/broadcasting. 

Adding Prometheus support to this project shouldn't be difficult, so sure, that's something I can look into.

The plan remains to eventually merge both projects
