### ISSUE TITLE
doh-proxy 0.9.6 deb package incompatible with latest Debian libc6

### ISSUE THREAD

**Issue by Dr-Escher** [DNSCrypt/doh-server#93]
The recently released [doh-proxy_0.9.6_amd64.deb package](https://github.com/DNSCrypt/doh-server/releases/tag/0.9.6) is incompatible with Debian's current 11.6 stable version, whereas prior doh-proxy_0.9.4_amd64.deb installs and works fine.

Attempting to upgrade the package results in
```
The following packages have unmet dependencies:
 doh-proxy : Depends: libc6 (>= 2.34) but 2.31-13+deb11u5 is to be installed
```

```
# apt list libc6
libc6/stable,stable-updates,now 2.31-13+deb11u5 amd64 [installed]
```

I created this issue under the assumption that the package is intended for Debian Bullseye systems. If this is not the case, feel free to close.

**Comment by jedisct1** [comment]
It's for the system it's built on. I guess since the last time you installed it, GitHub updated the Ubuntu version (`ubuntu-latest`).

Do the `.tar.bz2` files work on your system?

**Comment by jedisct1** [comment]
The `cargo zigbuild` command produces an executable for any target (even without dependencies). This is easy to use and what is used for the tarballs.

The `cargo deb` command produces an executable and creates a Debian package.

But there's no command that combines these two commands, so finding [the proper incantation](https://github.com/DNSCrypt/doh-server/commit/b81cc3e5d2a4886713c817646cb2083431ea489f) was not easy.

**Comment by jedisct1** [comment]
Debian packages for x86_64 and aarch64 have been added to the current release. Thanks!
