### ISSUE TITLE
Crash when using certs (clap?)

### ISSUE THREAD

**Issue by MeganerdNL** [DNSCrypt/doh-server#94]
When I start with:

`./doh-proxy -p /dns-query -u 172.17.0.2:553 -H mydomain.org  -i /opt/acme.sh/certs/mydomain.org/fullchain.pem -I /opt/acme.sh/certs/mydomain.org/mydomain.org.pkcs8.pem`

I get a crash:

```
thread 'main' panicked at 'Mismatch between definition and access of `tls_cert_path`. Could not downcast to TypeId { t: 2123382240168030213 }, need to downcast to TypeId { t: 9339889987678504387 }
', /home/myusername/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-4.0.32/src/parser/error.rs:30:9
```

I made sure the keyfile was converted to pkcs8 and I converted the fullchain also to pem format, but I get the same error when I use the fullchain.cer file instead of the fullchain.pem file. I also tried putting everything in one file (fullchain en key) and then use the same for -i en -I but always the same result. I use certificates from the acme script, in this case ZeroSSL. Should I switch to Let's Encrypt? or is this a bug or shortcomming in clap?

**Comment by jedisct1** [comment]
Thanks!

The Rust ecosystem is still very unstable; breaking changes happen constantly, and it's easy to introduce bugs while trying to keep up with theses API changes.

fbf8206 should fix it, and I'm going to publish a new version right now.

Thanks again!
