### ISSUE TITLE
RPM package pls?

### ISSUE THREAD

**Issue by Mosesofmason** [DNSCrypt/doh-server#98]
Is there an RPM precompile package available?

**Comment by jedisct1** [comment]
Hi!

I didn't see any, but you can convert a Debian package into an RPM package using the `alien` tool.

**Comment by jedisct1** [comment]
0.9.11 was released and includes RPM files. But as I don't use any RPM-based system, I don't know if these package work. Try them and tell me!

**Comment by SergeyDjam** [comment]
Hello. D'nt warry, i'm builded rpm

https://abf.io/build_lists/5056171 build list and rpm packages 0.9.11 version
https://abf.io/djam/doh-server - sources spec

**Comment by Mosesofmason** [comment]
@jedisct1 Thanks, but I could not find it in the release file list 
![image](https://github.com/DNSCrypt/doh-server/assets/161946/f67fe3ed-cc36-4f52-b993-e53a0600ee83)

@SergeyDjam Thank you, I will try it later!
